### ISSUE TITLE
Размещение результатов поиска

### ISSUE THREAD

**Issue by Sergei-Litvinov** [tigran123/urantia-book-explorer#11]
Предлагаю подумать о том, чтобы переформатировать размещение результатов поиска. **Я предлагаю выделить для этого не вертикальный столбец (как сейчас). а горизонтальную полосу.** При этом при переходе в режим поиска предоставлять экран (ниже основного меню) для результатов поиска и отображения текста, соответствующего фрагмента поиска. Переключение в режим просмотра текста осуществляется нажатием в меню на активный столбец, а возврат к поисковому контексту нажатием в меню на "поиск". Таким образом будет обеспечен динамичный просмотр как текста, так и результатов поиска. При этом предполагается, что возврат осуществляется к запомненному месту текста и поиска. В нынешнем формате мне кажется, что экран перегружен и отображение результатов поиска в виде столбца уже не будет привязано к текущему фрагменту текста активного столбца, т.к. поиск идет по всей КУ.

**Comment by tigran123** [comment]
Я не совсем понял описанную тобой схему. Вот мои вопросы:

1. Ты говоришь "для результатов поиска и отображения текста, соответствующего фрагмента поиска", но ведь это одно и тоже. Т.е. "результаты поиска" это и есть список соответствующих фрагментов текста в которых найдено совпадение по ключевой фразе.

2. Ты говоришь о переключении между результатами поиска и текста нажатием на какие-то кнопки, но зачем нужно переключаться, если и так на экране будет видно и то и другое? Просто води мышкой (или пальцем передвигай на тачскрине) и соответствующий столбец реагирует --- зачем специально "переключаться"?

**Comment by Sergei-Litvinov** [comment]
1. Результат поиска - аннотации поисковых фрагментов (формат 1) и общий анализ поискового запроса: найдено/не найдено столько-то фрагментов;
2. Далее при входе в конкретный поисковый фрагмент "проваливаемся" в текст соответствующего документа (формат 2);
3. Поскольку возможно 2 состояния при поиске: (формат 1) и (формат 2) надо предусмотреть возможность переключения между форматами, т.к. например (формат 2) может занимать весь экран и возврат к режиму просмотра текста без поиска с такого экрана надо как-то сделать;
4. При горизонтальном окне поиска одновременно текст для чтения и поисковый контекст будут недоступны, поэтому мышкой управлять не получится.

**Comment by tigran123** [comment]
Я добавил одну из функций, которые мы обсуждали, а именно "сделать активный текст видимым при клике из результатов поиска" (см. коммит b3e011522b2e418e91d733e8a4d04a44dc8e72ad). А над остальными вещами надо конечно подумать...

**Comment by tigran123** [comment]
Мы подумали и решили, что в данный момент острой необходимости изменения дизайна столбца результатов поиска нет.
