### ISSUE TITLE
Какой формат текста, используемого в поисковике?

### ISSUE THREAD

**Issue by alyuev** [tigran123/urantia-book-explorer#12]
Тигран, ты говоришь сделать скрипт по преобразованию, например, FB2, результатом которого должен быть текст, аналогичный результату твоего скрипта для sed.

А не мог бы ты выложить формат финального текста, который используется в поиске?

**Comment by tigran123** [comment]
Да, сделал уже, вот: 

[http://quantuminfodynamics.com/ubex/](http://quantuminfodynamics.com/ubex/)

**Comment by tigran123** [comment]
У меня у самого, кстати сейчас такая же задача --- написать скрипт, который извлекает и текст и заметки из British Study Edition of the Urantia Papers и конвертирует в формат, удобоваримый для нашего сайта.
