### ISSUE TITLE
Количество совпадений результата поиска

### ISSUE THREAD

**Issue by alyuev** [tigran123/urantia-book-explorer#13]
Добавить строку с количеством совпадений искомой строки в результатах поиска "Найдено ... совпадений". Например, в заголовок колонки "Результаты". Или первой строкой в колонке результатов.

**Comment by tigran123** [comment]
Да, это обязательно нужно. Лучше всего в заголовок, чтобы во время скроллинга не надо было возвращаться к началу, чтобы вспомнить сколько же всего результатов.

Для этого `search.php` должен не просто выплёвывать строки через `echo`, а складывать их в структуру и в конце "выплюнуть" одним разом посредством `echo json_encode($json);`  а на том конце (т.е. JS) декодировать содержимое структуры. Я это уже делал в своей предыдущей работе несколько лет назад, так что проблем не должно быть...

**Comment by tigran123** [comment]
Fixed by commit 696a8d9ba46fa9e99d11b658e58b09e82e39de80 except that the results are still unnumbered, so I am leaving this issue open to remind that we need to enumerate the results.

**Comment by tigran123** [comment]
The commit cdb7ee9cdc7bc0f1659798a140f11a92c4b55071 closes this issue.
