### ISSUE TITLE
F1 close

### ISSUE THREAD

**Issue by alyuev** [tigran123/urantia-book-explorer#2]
It's can't close F1 tooltip without pressing F1. For example on touchscreen.

**Comment by tigran123** [comment]
Click on the "?" button --- the last button in the "Explorer Control Panel"

**Comment by alyuev** [comment]
I know, but tooltip is over this button.

**Comment by tigran123** [comment]
Ok, but it is draggable --- can't you drag it away from it?

**Comment by tigran123** [comment]
Well, we can implement a little cross which closes it, I suppose.

**Comment by alyuev** [comment]
Ah! Got it!
