### ISSUE TITLE
Add main search history

### ISSUE THREAD

**Issue by alyuev** [tigran123/urantia-book-explorer#20]
Сделать в виде меню по кнопке справа в поле ввода строки поиска, или показывать по мере ввода текста.

**Comment by tigran123** [comment]
Да, это нужная и полезная вещь. А в будущем (версия 2) можно даже хранить все уникальные поиски всех пользователей в базе данных и как-то анализировать эту информацию ;)

**Comment by alyuev** [comment]
Да, было бы интересно. Тогда можно будет понять - будут ли пользоваться, например, продвинутым поиском с помощью операторов/метасимволов? Например "слово1 /3 слово3" - ищем слова на расстоянии 3х слов друг от друга. Как это сделано в Яндекс.Поиске.

**Comment by alyuev** [comment]
Эту ветку, наверное, можно закрыть...
