### ISSUE TITLE
Считать ли ошибкой результат поиска "htm" или "href"?

### ISSUE THREAD

**Issue by alyuev** [tigran123/urantia-book-explorer#25]
Находит результат в тэгах типа `<a href="TextStandardization.htm#U0_1_24"> *</a>`

Может это не считать ошибкой, а использовать результат в плюс? Т.е. принять за опцию, что можем искать в тексте использование ссылок....

**Comment by tigran123** [comment]
Проблема возникает не при поиске "htm" или "href", а при поиске того, что встречается и в нормальном тексте, например "*0*" наряду с числами содержащими цифру 0 выдаёт огромное количество мест со ссылкой типа "U40_8_5" которые даже жёлтым не выделяются. Желательно было бы от них избавиться, если возможно...

**Comment by tigran123** [comment]
коммит 0fe6c1215269ebae7abb7160867afacaae159e13 решает эту проблему.
