### ISSUE TITLE
Пробел после слова съедается при поиске по заголовкам

### ISSUE THREAD

**Issue by tigran123** [tigran123/urantia-book-explorer#29]
Например, поиск "Urantia" по заголовкам английского текста приводит к таким результатам как "UrantiaSolar System", "UrantiaAtmosphere" и т.д.

Но если у нас будет специализированный поиск по Оглавлению, то этот баг чинить не обязательно --- просто селектор "Текст/Текст+Заголовки/Заголовки" исчезнет и с ним соответствующий код в `search.php`....

**Comment by alyuev** [comment]
Да, там же preg_filter используется, а не preg_replace_callback. И я потому и не занимался переделкой поиска по ТОС, потому что в будущем по нему будет отдельный.

**Comment by tigran123** [comment]
Да, согласен. И раз причина теперь ясна, то этот вопрос можно и закрыть.
