### ISSUE TITLE
Open column without Ctrl+

### ISSUE THREAD

**Issue by alyuev** [tigran123/urantia-book-explorer#3]
There is no ability to open new column without pressing Ctrl+... on touchscreen.

**Comment by tigran123** [comment]
You are right. And how do you propose to implement it?

What we could do is to add extra buttons for TOC, Notes and Search Results (like the 1,2,3 buttons) in the panel and leave them (but perhaps cross or indicate in some other way that the corresponding column is gone) when the column is closed. And if you want to re-open the column just click on that button.

Or do you have a better idea?

**Comment by alyuev** [comment]
In "Settings" tab to add table or list of columns. Item in the list will be the column on main page. Order of items corresponds on order of column. Double-click on item will select type of column: TOC, text, notes e.t.c.

**Comment by tigran123** [comment]
Hmmm, if I understood you correctly it would mean that any column manipulation would require having to switch to the Settings tab, which is not good. It would be nice to do this while staying in the main tab.

**Comment by tigran123** [comment]
Кстати, никто нам здесь не запрещает говорить по-русски :)

**Comment by alyuev** [comment]
Понимаю. Просто мало ли кто будет читать.

**Comment by alyuev** [comment]
По сути список нужен как раз на этапе настройки работы и как помощь для тачскрина. Остальные с легкостью сделают это с помощью Ctrl+...

**Comment by alyuev** [comment]
Если сделать настраиваемый список - это будет универсально - сразу настройка количества колонок, порядок и их тип.

**Comment by alyuev** [comment]
Фантазируя дальше можно даже будет сделать тип колонки "настройка", и в такой колонке выводить этот самый список на главной странице. И в ней же (в этой колонке), например показывать дополнительные опции-флажки помимо списка колонок.

**Comment by tigran123** [comment]
В принципе хорошая идея --- я тоже думал, что ограничивать 3-мя текстовыми столбцами глупо --- у кого-то может быть 32" экран с огромным разрешением и тогда можно и 4 и даже 5 текстовых столбцов поместить.

Насчёт порядка не уверен --- колонки можно сделать "draggable" и тогда можно просто переставлять их "на лету".

**Comment by alyuev** [comment]
Тогда можно просто добавить на главной странице, например в секции Панель управления, кнопку "+" с выпадающим меню, в котором перечислить виды колонок. Это в том случае, если будет работать перетаскивание колонок.

**Comment by tigran123** [comment]
Погоди,  я сначала хочу попробовать более простой вариант --- исключить кнопки 1,2,3 из класса который делается невидимым при удалении столбца. Если этот подход сработает, тогда не надо усложнять излишне. А если нет, тогда подумаем над твоей идеей.

**Comment by tigran123** [comment]
Ну вот, более простой вариант работает вполне. Пока я починил только для текстовых столбцов, но можно добавить кнопки и для Оглавления и для Заметок и для Результатов поиска, конечно. Но это будет завтра --- утро вечера мудренее. Пойду спать, а точнее читать :)

**Comment by tigran123** [comment]
Ах, один маленький баг всё-таки есть --- если убрать _последний_ столбец, то чтобы его вернуть, надо сначала вернуть какой-нибудь другой столбец, а потом уже его. Завтра починим, не беда.

**Comment by tigran123** [comment]
Ну вот, я же говорил --- утро вечера мудренее. Починил проблему с возвратом последнего текстового столбца (без клавиатуры).

Теперь будем разбираться с остальными тремя столбцами: Оглавление, Заметки и Результаты поиска.

**Comment by tigran123** [comment]
Там ещё есть баг: при закрытии столбца Оглавления активный текстовый соскакивает всегда на 1-й, а должен оставаться на месте. Щас исправим...

**Comment by tigran123** [comment]
Коммит be4e9d0622d9ca772372dd5a789ce1b858da2ef8 решает проблему данного вопроса, так что если возражений нет, предлагаю этот вопрос закрыть.
