### ISSUE TITLE
Предлагаю сделать активизацию колонки по шапке

### ISSUE THREAD

**Issue by alyuev** [tigran123/urantia-book-explorer#34]
Сейчас, чтобы активизировать нужную колонку для поиска по ней, необходимо в панели управления кликнуть на кнопке с соответствующим номером колонки. 
Предлагаю это делать (активировать) и по клику на шапке самой колонки.

**Comment by tigran123** [comment]
Сначала так оно и было, но очень неудобным был тот факт, что нажимая на любой под-элемент шапки (скажем на стрелки или селектор) вызывалось переключение активного текста. Этого не должно случаться. Но если закодировано правильно, т.е. учитываются только клики _вне_ активных элементов, но _внутри_ шапки, то я согласен --- это хорошая идея.

**Comment by tigran123** [comment]
Сразу скажу, что проверять внутри клик-handler-а и "уворачиваться" от ненужных событий (т.е. _первое_ что приходит в голову) --- неправильное решение. Правильное, это подобрать такой jQuery селектор, чтобы фильтрация событий происходила на низшем, т.е. системном jQuery, уровня, а до программы эти события вообще не доходили.

**Comment by tigran123** [comment]
Этот вариант работает, но не идеально, а именно кликать нужно либо на название Документа, либо по сторонам от него. Но не слишком высоко :)
