### ISSUE TITLE
Present shorter context in Search Results

### ISSUE THREAD

**Issue by tigran123** [tigran123/urantia-book-explorer#4]
I think it would be a good idea to show not the entire paragraph but a shorter context (like the way it is done by urantia.ru) around the match. This will save vertical space in the Search Results column.

Also, multiple matches in the same paragraph should be counted separately.

**Comment by tigran123** [comment]
But before we even attempt this we need to figure out how to do the search at all :)

Currently `search.php` does a grep of the source html files, but this has one major problem --- the html files have a "<em>" tag used for italics and so, for example, we can't find the first occurrence of "local universe of Nebadon" because in it "Nebadon" happens to be in italics.

So, we need a strategy of avoiding these italic tags, for example:

* Directly coding a regex to ignore them (e.g. via passing the stream through sed)

* Reading each p???.html file into memory via PHP and analysing it there

I feared that direct search/analysis in PHP is going to be much slower than invoking external utilities like fgrep and sed, but, given the amount of complex stuff that we probably want to perform with the matches (extracting context etc), it would seem that we'll have to go the hard way and do it in PHP...

But I welcome any alternative suggestions, of course.

**Comment by alyuev** [comment]
Not only <em> tag, but Russian text may contains accented vowels.

**Comment by tigran123** [comment]
The current Russian UF text, as you explained in #6 doesn't use those accents, so at the moment it is only `<em>` that we have to deal with.

**Comment by alyuev** [comment]
На JavaScript я бы сделал так: 			
```
res_row = res_row.replace(/(«|»)/g, ""); //убираем русские елочки
res_row = res_row.replace(/<\/?([ib]|em)>/g, "");//убираем тэги <i>, <b>,<em> вместе с закрывающими
```

**Comment by tigran123** [comment]
Да, ёлочки и кавычки тоже надо при поиске убирать конечно, спасибо, что напомнил.

**Comment by tigran123** [comment]
I am experimenting with doing the search directly in PHP, without having to invoke external commands like fgrep/sed and it is looking quite good --- it is much faster than I expected. I thought it would be 5-6 times slower than using fgrep, but it is only about 2-3 times slower and I may be able to optimise it a bit to make it as fast as PHP can get :)

**Comment by tigran123** [comment]
Шустро, да не очень --- это я насчёт поиска на модифицированном движке Барри на urantia-s.com. А именно, поищи "local universe of Nebadon" --- да, место 0:0.5 (с <em>Nebadon</em>) он находит, но в результатах поиска Nebadon жёлтым цветом остаётся без <em></em> а должен оставаться внутри <em></em>...

**Comment by tigran123** [comment]
Да, действительно, что вроде этого работает прекрасно:

```
   $text = '(<em>)?local(<\/em>)? (<em>)?universe(<\/em>)? of (<em>)?Nebadon(<\/em>)?';
   $pattern = ['/('.$text.')/'];
   $replace = ['<span style="background-color:yellow;">$1</span>'];
   if ($ic) $pattern[0] .= "i"; 
   for ($i = $ic_min; $i <= $ic_max; $i++) {
      $filename = sprintf("text/" . $mod_idx . "/p%03d.html", $i);
      $lines = file($filename);
      foreach($lines as $line) {
         $count = 0;
         $matched_line = preg_replace($pattern, $replace, $line, -1, $count);
         if ($count > 0) echo $matched_line;
      }
   }
```

Теперь надо просто закодировать, чтобы не только "local universe of Nebadon" а любую фразу искал правильно, т.е. использовать php `explode()/implode()` функции, чтобы оборачивать каждое слово в условное `(<em>)?` и `(<\/em)?`.

**Comment by alyuev** [comment]
По идее с точкой должна помочь такая конструкция замены экранированием:
`$pattern = preg_replace('/(\.)/u', '\\\\$1', $pattern);`

Но сходу у меня не получилось.

**Comment by tigran123** [comment]
Нужно позаботиться не только о точке, но и о запятой, точке-запятой, восклицательном и вопросительном знаках, а также кавычках и ёлочках --- всё это должно оказаться внутри `<em>` и `</em>` в `$pattern`.

**Comment by alyuev** [comment]
Добавил улучшение поиска

**Comment by tigran123** [comment]
Solved by the PR #87
