### ISSUE TITLE
Допускать возможность более одной гиперссылки в параграфе текста

### ISSUE THREAD

**Issue by tigran123** [tigran123/urantia-book-explorer#40]
В данный момент `search.php` подразумевает не более одной гиперссылки на параграф:

[https://github.com/tigran123/urantia-book-explorer/blob/master/search.php#L98](https://github.com/tigran123/urantia-book-explorer/blob/master/search.php#L98)

Но для импорта текста и аннотаций _The British Study Edition of the Urantia Papers_ (см. #31 ) необходимо разрешить более одной аннотации на параграф.

**Comment by tigran123** [comment]
Погоди, а для чего это было нужно? Уже сейчас, поиск по "href" ничего не показывает, т.е. проблемы вроде бы нет?

**Comment by alyuev** [comment]
В результатах поиска вернутся не все ссылки, а первая. Т.е. во всех местах параграфа будет одна и та же ссылка.

**Comment by tigran123** [comment]
Понял, спасибо.

**Comment by tigran123** [comment]
Кстати, пока я не починю #43 менять `search.php` не нужно. Т.е. формат ссылки может измениться...
