### ISSUE TITLE
Формат панели исследователя

### ISSUE THREAD

**Issue by Sergei-Litvinov** [tigran123/urantia-book-explorer#52]
Предлагаю перекомпоновать панели исследователя и поиска таким образом, чтобы они размещались в одну строку по всей ширине экрана. Если не будет "влазить", то можно некоторые настройки (а=А) переместить в "настройки" основного меню.

**Comment by tigran123** [comment]
То, что ты предлагаешь уже сделано, т.е. так и было с самого начала. Вот посмотри как выглядит Исследователь на моём экране в разрешении FullHD (1920x1080):

![Screenshot of UBE](http://www.bibles.org.uk/screenshots/UBE.png)

Если у тебя выглядит иначе, это значит, что просто места не хватило на экране и одна из панелей съехала вниз. Кстати, это "съезжание вниз" намного лучше, чем если бы она вылезала вправо и приходилось скролить по горизонтали. Т.е. наш дизайн "адаптивный" --- он адаптирует себя к имеющемуся горизонтальному пространству.
