### ISSUE TITLE
Акцентированные гласные в русском тексте

### ISSUE THREAD

**Issue by alyuev** [tigran123/urantia-book-explorer#6]
В текущей версии русского текста (UF 1997-1.9) акцентированных гласных нет. С одной стороны для чтения это удобно - разрешается спорное трактование текста, указывается смысл конкретным ударением. Но для реализации поиска - акцент не удобен.  Если удастся реализовать правильный поиск с учетом ацентов - планируется ли добавление в русский текст выделение таких гласных?

**Comment by tigran123** [comment]
Мы используем текст Фонда (urantia.org) и там этих акцентов нет. Но, в моей репозитории в TeX формате (сгенерированном с твоего fb2  файла) эти акценты есть. В принципе, можно написать скрипт, который генерирует то, что нам надо, но с акцентами. Но тогда нужно ещё сделать, чтобы и поиск работал. Ты спрашиваешь "планируется ли?" --- сначала не планировалось, но кто мешает тебе сделать описанную тобой же работу и тогда не-запланированное станет реальностью :)

Давай определимся с поиском сначала, как мы его будем делать --- продолжать в духе fgrep/sed или читать файл в php и анализировать "вручную", а уже исходя из этого, будет ясно, стоить возиться с акцентами в русском тексте или нет. Если пойдём путём fgrep/sed, то наверное не стоит, а если всё равно придётся текст анализировать на уровне php, тогда акценты не намного усложнят жизнь и можно будет их добавить.

**Comment by tigran123** [comment]
Насчёт акцентированных гласных, сделаем так:

1. Имеющийся в данный момент текст оставим как есть, ибо это 3-е издание и скачано с urantia.org абсолютно без изменений (кроме исправленных технических дефектов, но сам текст оставлен как есть).

2. Мы можем добавить текст 4-го издания (или сразу 5-го?) в котором есть акценты. Если хочешь, ты можешь заняться этим --- написать скрипт конверсии твоего же fb2 файла, чтобы результат был такой же как в результате этого скрипта:

https://github.com/tigran123/urantia-book-explorer/blob/master/tools/russian/mktext.sh

**Comment by tigran123** [comment]
Вопрос получил ответ, значит его можно закрыть.
