### ISSUE TITLE
поиск по укороченному номеру главы 

### ISSUE THREAD

**Issue by Sergei-Litvinov** [tigran123/urantia-book-explorer#72]
не проходит поиск, например: 36:5 не находит, находит только 36:5.0

**Comment by tigran123** [comment]
Спасибо. Очень хорошая идея, я этим и займусь.

**Comment by tigran123** [comment]
Всё, готово, можешь попробовать. Поиск по "24:0" приводит к началу 24-го документа, а поиск по "24:3" приводит к его 3-й главе.
