### ISSUE TITLE
Ошибка при копировании заголовка колонки результатов.

### ISSUE THREAD

**Issue by alyuev** [tigran123/urantia-book-explorer#75]
Если выделить в заголовке колонки результатов часть текста, например в "РЕЗУЛЬТАТЫ ПОИСКА (403/161)" выделить только 2(403/161)", то колонка закрывается. Если выделить весь текст - колонка остается на месте.

**Comment by tigran123** [comment]
Да, действительно, у меня происходит так же. Надо починить.

**Comment by tigran123** [comment]
Если просто кликнуть на заголовок результатов, он исчезает тоже. Я займусь этим.

**Comment by tigran123** [comment]
А, всё ясно: столбец результатов и заметок попадают в класс `coltitle` и поэтому вызывается функция, которая закрывает эти столбцы при кликании в области текста заголовка. Я подумаю, как перегруппировать классы, чтобы этого не случалось.
